// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web is not configured.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Platform not supported.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9_2selrilY01TrvqcHzfloF_CPnZJryM',
    appId: '1:142318041024:android:9d784a34b2f29f1295f12e',
    messagingSenderId: '142318041024',
    projectId: 'skill-scanner-de21e',
    storageBucket: 'skill-scanner-de21e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsfXiyX2u1bqeyDsz39r5TB5fPYkYdmU4',
    appId: '1:142318041024:ios:e08f5d7285913f4295f12e',
    messagingSenderId: '142318041024',
    projectId: 'skill-scanner-de21e',
    storageBucket: 'skill-scanner-de21e.firebasestorage.app',
    iosBundleId: 'Ziggurat-pm.skillScanner',
  );
}
